# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bvh}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin MacKenzie IV (sinisterchipmunk)"]
  s.date = %q{2010-10-02}
  s.description = %q{A library for loading, modifying and saving BVH motion capture files.}
  s.email = %q{sinisterchipmunk@gmail.com}
  s.extensions = ["ext/bvh/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "EXAMPLES.rdoc",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bvh.gemspec",
     "ext/bvh/Makefile",
     "ext/bvh/bvh.c",
     "ext/bvh/bvh.h",
     "ext/bvh/bvh_parser.c",
     "ext/bvh/extconf.rb",
     "lib/bvh.rb",
     "lib/bvh/exporter.rb",
     "lib/bvh/matrix.rb",
     "lib/bvh/motion.rb",
     "lib/bvh/motion/channel_data.rb",
     "lib/bvh/motion/frame.rb",
     "lib/bvh/parser.rb",
     "lib/bvh/skeleton.rb",
     "test/bvh_test.rb",
     "test/data/in/karate.bvh",
     "test/helper.rb"
  ]
  s.homepage = %q{http://github.com/sinisterchipmunk/bvh}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A library for loading, modifying and saving BVH motion capture files.}
  s.test_files = [
    "test/bvh_test.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

